build:
	gcc p1_print_larger_then_10byte.c -o print_larger_then_10byte
	gcc p2_hole_1kb.c -o hole_1kb
	gcc p3_create_dir_and_file.c -o create_dir_and_file
	gcc p4_delete_file_largerthen_100bytes.c -o delete_file_largerthen_100bytes
	gcc p5_offset_delete.c -o offset_delete
	gcc p6_hole_truncate.c -o hole_truncate

clear:
	rm -rf print_larger_then_10byte  hole_1kb create_dir_and_file delete_file_largerthen_100bytes offset_delete hole_truncate
