build:
	gcc p1_i_o_redirection.c -o i_o_redirection
	gcc p2_new_directory.c  -o new_directory
	gcc p3_file_compair.c  -o file_compair
	gcc p4_10byte_copy.c -o 10byte_copy_from_dir_to_demo
	gcc p5_lseek.c -o lseek_20_bytes

clear:
	rm -rf i_o_redirection  new_directory file_compair 10byte_copy_from_dir_to_demo lseek_20_bytes
