build:
	gcc p1_print_file_indir.c -o file_names
	gcc p2_print_file_indir_types.c -o file_type
	gcc p3_print_largest.c -o large_file
	gcc p4_copy_full_file.c -o copy_file_local
	gcc p5_check_file_present_dir.c -o file_present_in_dir
	gcc p6_dir_allfile_move.c -o dir_to_dir_file_copy
	gcc p7_delete_empty_files.c -o delete_empty_file

clean:
	rm -rf file_names file_type  large_file  copy_file_local file_present_in_dir dir_to_dir_file_copy delete_empty_file bbb/a.txt bbb/b.txt bbb/c.txt

